# Generated by Django 4.0.6 on 2022-07-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('service_charge', models.CharField(max_length=10)),
                ('surge_charge', models.CharField(max_length=10)),
                ('initial_charge', models.CharField(max_length=10)),
                ('km_rate', models.CharField(max_length=10)),
            ],
        ),
    ]
