# Generated by Django 4.0.6 on 2022-07-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fare',
            name='initial_charge',
        ),
        migrations.RemoveField(
            model_name='fare',
            name='km_rate',
        ),
        migrations.RemoveField(
            model_name='fare',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='fare',
            name='surge_charge',
        ),
        migrations.AddField(
            model_name='fare',
            name='distance',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_charge', models.CharField(max_length=10)),
                ('surge_charge', models.CharField(max_length=10)),
                ('initial_charge', models.CharField(max_length=10)),
                ('km_rate', models.CharField(max_length=10)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='calculator.time')),
            ],
        ),
    ]
